package gui;


import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ELVIS
 */
public class Formulario extends javax.swing.JFrame implements ClipboardOwner {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }
    public void setClipboard(String texto){
        StringSelection txt=new StringSelection(texto);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(txt, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        cboMotivo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTicket = new javax.swing.JTextField();
        txtCoordenadas = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCto = new javax.swing.JTextField();
        txtLID9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboDistrito = new javax.swing.JComboBox<>();
        cboContrata = new javax.swing.JComboBox<>();
        txtLID = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtNomTecnico = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtResultado2 = new javax.swing.JTextArea();
        btnCopiarNuevo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnCopiar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTextoGrande = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        btnMostrarTextoGrande = new javax.swing.JButton();
        btnClienteDesconectad = new javax.swing.JButton();
        btnSplitter = new javax.swing.JButton();
        txtPuerto = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cboDistrito2 = new javax.swing.JComboBox<>();
        cboContrata2 = new javax.swing.JComboBox<>();
        btnValidacionCableado = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCambiosONT = new javax.swing.JButton();
        btnCambiosCTONAP = new javax.swing.JButton();
        btnRematriculacion = new javax.swing.JButton();
        btnValidacionDanDetec = new javax.swing.JButton();
        btnValidacionLlamada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "POTENCIA DEGRADADA", "SIN POTENCIA", "PUERTOS SIN POTENCIA", "PUERTOS DEGRADADOS", "CTO ROBADA" }));
        cboMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMotivoActionPerformed(evt);
            }
        });

        jLabel6.setText("Motivo NAP /  CTO:");

        jLabel7.setText("Ticket:");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Cliente:");

        txtTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTicketActionPerformed(evt);
            }
        });

        txtCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoordenadasActionPerformed(evt);
            }
        });

        jLabel14.setText("Coordenadas:");

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        jLabel10.setText("CTO/ NAP (Piso):");

        txtCto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCtoActionPerformed(evt);
            }
        });

        txtLID9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txtLID9.setText("X");
        txtLID9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLID9ActionPerformed(evt);
            }
        });

        jLabel11.setText("Puerto:");

        jLabel1.setText("Contrata:");

        jLabel12.setText("Distrito:");

        jLabel2.setText("Direccion:");

        cboDistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Ancón", "Ate", "Barranco", "Breña", "Carabayllo", "Cercado de Lima", "Chaclacayo", "Chorrillos", "Cieneguilla", "Comas", "El agustino", "Independencia", "Jesús maría", "La molina", "La victoria", "Lince", "Los olivos", "Lurigancho", "Lurín", "Magdalena del mar", "Miraflores", "Pachacámac", "Pucusana", "Pueblo libre", "Puente piedra", "Punta hermosa", "Punta negra", "Rímac", "San bartolo", "San borja", "San isidro", "San Juan de Lurigancho", "San Juan de Miraflores", "San Luis", "San Martin de Porres", "San Miguel", "Santa Anita", "Santa María del Mar", "Santa Rosa", "Santiago de Surco", "Surquillo", "Villa el Salvador", "Villa Maria del Triunfo" }));
        cboDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDistritoActionPerformed(evt);
            }
        });

        cboContrata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "DIGETEL", "OLMA", "KAJOMI", "MALLAUSA", "SGM", "VCONNECTIONS", "CESPEDES", "ALL TELECOM", "ONI", "DATANTENNA" }));
        cboContrata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboContrataActionPerformed(evt);
            }
        });

        txtLID.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txtLID.setText("X");
        txtLID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLIDActionPerformed(evt);
            }
        });

        jLabel17.setText("Contrata:");

        txtNomTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomTecnicoActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane6.setViewportView(txtResultado);

        jLabel18.setText("Tecnico que reporta:");

        txtResultado2.setColumns(20);
        txtResultado2.setRows(5);
        jScrollPane7.setViewportView(txtResultado2);

        btnCopiarNuevo.setText("Copiar");
        btnCopiarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarNuevoActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCopiar2.setText("Copiar");
        btnCopiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiar2ActionPerformed(evt);
            }
        });

        txtTextoGrande.setColumns(20);
        txtTextoGrande.setRows(5);
        jScrollPane1.setViewportView(txtTextoGrande);

        btnMostrarTextoGrande.setText("Copiar");
        btnMostrarTextoGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTextoGrandeActionPerformed(evt);
            }
        });

        btnClienteDesconectad.setText("Cliente desconectado");
        btnClienteDesconectad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteDesconectadActionPerformed(evt);
            }
        });

        btnSplitter.setText("Utilizacion de Splitter");
        btnSplitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplitterActionPerformed(evt);
            }
        });

        txtPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuertoActionPerformed(evt);
            }
        });

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });

        jLabel9.setText("DNI:");

        jLabel19.setText("Distrito:");

        cboDistrito2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Ancón", "Ate", "Barranco", "Breña", "Carabayllo", "Cercado de Lima", "Chaclacayo", "Chorrillos", "Cieneguilla", "Comas", "El agustino", "Independencia", "Jesús maría", "La molina", "La victoria", "Lince", "Los olivos", "Lurigancho", "Lurín", "Magdalena del mar", "Miraflores", "Pachacámac", "Pucusana", "Pueblo libre", "Puente piedra", "Punta hermosa", "Punta negra", "Rímac", "San bartolo", "San borja", "San isidro", "San Juan de Lurigancho", "San Juan de Miraflores", "San Luis", "San Martin de Porres", "San Miguel", "Santa Anita", "Santa María del Mar", "Santa Rosa", "Santiago de Surco", "Surquillo", "Villa el Salvador", "Villa Maria del Triunfo" }));
        cboDistrito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDistrito2ActionPerformed(evt);
            }
        });

        cboContrata2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "DIGETEL", "OLMA", "KAJOMI", "MALLAUSA", "SGM", "VCONNECTIONS", "CESPEDES", "ALL TELECOM", "ONI", "DATANTENNA" }));
        cboContrata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboContrata2ActionPerformed(evt);
            }
        });

        btnValidacionCableado.setText("Validacion de cableado a realizar");
        btnValidacionCableado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidacionCableadoActionPerformed(evt);
            }
        });

        jButton2.setText("Utilizacion de cliente de baja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCambiosONT.setText("Cambio de ONT");
        btnCambiosONT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiosONTActionPerformed(evt);
            }
        });

        btnCambiosCTONAP.setText("Cambio de CTO o caja NAP");
        btnCambiosCTONAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiosCTONAPActionPerformed(evt);
            }
        });

        btnRematriculacion.setText("Rematriculacion");
        btnRematriculacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRematriculacionActionPerformed(evt);
            }
        });

        btnValidacionDanDetec.setText("Validacion para daño detectado en las instalaciones parte cliente");
        btnValidacionDanDetec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidacionDanDetecActionPerformed(evt);
            }
        });

        btnValidacionLlamada.setText("Validacion de llamada");
        btnValidacionLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidacionLlamadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCto, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLID9)
                                    .addComponent(txtLID)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cboContrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCopiarNuevo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrarTextoGrande)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClienteDesconectad)
                                    .addComponent(btnSplitter))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel18))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtNomTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                                .addComponent(cboContrata2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel7))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtCoordenadas, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                                    .addComponent(cboMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cboDistrito2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel8)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCopiar2)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnValidacionDanDetec)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnRematriculacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCambiosCTONAP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCambiosONT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnValidacionCableado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnValidacionLlamada))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboContrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLID))
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLID9)
                            .addComponent(txtCto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCopiarNuevo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnCopiar2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(cboDistrito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboContrata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtNomTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cboMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnValidacionCableado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCambiosONT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCambiosCTONAP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRematriculacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnValidacionDanDetec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnValidacionLlamada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrarTextoGrande)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClienteDesconectad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSplitter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMotivoActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTicketActionPerformed

    private void txtCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoordenadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoordenadasActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCtoActionPerformed

    private void txtLID9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLID9ActionPerformed
        // TODO add your handling code here:
        txtCto.setText("");
    }//GEN-LAST:event_txtLID9ActionPerformed

    private void cboDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDistritoActionPerformed

    private void cboContrataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboContrataActionPerformed

   

        // TODO add your handling code here:
    }//GEN-LAST:event_cboContrataActionPerformed

    private void txtLIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLIDActionPerformed

        txtDireccion.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLIDActionPerformed

    private void txtNomTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomTecnicoActionPerformed

    private void btnCopiarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarNuevoActionPerformed
        // TODO add your handling code here:
        String datos,contrata,direccion,distrito,cto,puerto;
        
        contrata=cboContrata.getSelectedItem().toString();
        direccion=txtDireccion.getText();
        cto=txtCto.getText();
        puerto=txtPuerto.getText();
        distrito=cboDistrito.getSelectedItem().toString();
        
        datos="Traslado OK\n" +
        "Contrata :"+contrata+ "\n" +
        "Direccion:"+direccion+ " - "+distrito + "\n" +
        "CTO:"+cto+ "\n" +
        "PUERTO:"+puerto;

        txtResultado.setText(datos);
        setClipboard(datos);
    }//GEN-LAST:event_btnCopiarNuevoActionPerformed

    private void btnCopiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiar2ActionPerformed
        // TODO add your handling code here:
    
        String motivo,distrito,contrata;
        motivo=cboMotivo.getSelectedItem().toString();
        distrito=cboDistrito2.getSelectedItem().toString();
        contrata=cboContrata2.getSelectedItem().toString();
        
        String resultado="MOTIVO NAP/CTO: "+motivo+"\n" +
        "Cliente/a: "+txtCliente.getText()+"\n" +
        "Dni: "+txtDNI.getText()+"\n"+
        "Ticket: "+txtTicket.getText()+"\n" +
        "COORDENADAS: "+txtCoordenadas.getText()+"\n" +
        "Distrito: "+distrito+"\n"+
        "Contrata: "+contrata+ "\n" +
        "Tecnico que reporta: "+txtNomTecnico.getText()+"\n"+
        "Observaciones: ";
        txtResultado2.setText(resultado);
        setClipboard(resultado);

    }//GEN-LAST:event_btnCopiar2ActionPerformed

    private void btnMostrarTextoGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTextoGrandeActionPerformed
        // TODO add your handling code here:  
        
        String texto = "Ok compañero le brindo los clientes de baja, en caso lo ubique PORFAVOR ENVIAR FOTO DEL CINTILLO Y VALIDE QUE EL PUERTO COINCIDA CON LO INDICADO \n"
                + "\n"
                + "****************************************************\n"
                +txtTextoGrande.getText()+"\n"
                + "****************************************************\n"
                + "Tener en cuenta el siguiente criterio:\n" 
                +"\n" 
                +"⚠ En caso no lo ubique en el puerto brindado o indica puerto no identificado, porfavor indicar con la plantilla correspondiente para poder tener en cuenta y se realice la validación correspondiente para confirmar si procede o no y en caso se le brinda la autorización pueda proceder - Tener en cuenta que si el técnico realizo la gestión sin confirmación del gestor a cargo, el caso será reportado por omitir el proceso correcto.\n" +
                "\n" +
                "♻ No olvide de CORREGIR EL CINTILLO CON EL PUERTO INDICADO PARA REPONER EL SERVICIO DEL CLIENTE/ ATENDIDO Y ENVIAR EVIDENCIA DEL CABLE CORTADO Y CINTILLO RETIRADO DEL CLIENTE/A DE BAJA UTILIZADO ❌\n" +
                "\n" +
                "Recuerde que el uso de la plantilla es obligatorio y de no hacerlo el gestor a cargo etiquetara al líder técnico y se reportara a los encargados de la contrata.\n" +
                "\n" +
                "TICKET: \n" +
                "CLIENTE:\n" +
                "DNI:\n" +
                "CTO O CAJA NAP:\n" +
                "PUERTO UTILIZADO:\n" +
                "POTENCIA DE PUERTO UTILIZADO:\n" +
                "DNI DEL CLIENTE AFECTADO:\n" +
                "CONTRATA:";
        setClipboard(texto);
    }//GEN-LAST:event_btnMostrarTextoGrandeActionPerformed

    private void btnClienteDesconectadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteDesconectadActionPerformed
        // TODO add your handling code here:
        
        String texto = "TICKET:\n"
                + "CLIENTE(A) ATENDIDO\n"
                + "DNI DEL CLIENTE ATENDIDO:\n"
                + "CODIGO DE CTO O PISO DE CAJA NAP: \n"
                + "DIRECCION O NOMBRE DE EDIFICIO / CONDOMINIO / RESIDENCIAL:\n"
                + "PUERTO: \n"
                + "DNI DEL CLIENTE CONECTADO ACTUALMENTE EN EL PUERTO:\n"
                + "NOMBRE DEL TECNICO:\n"
                + "CONTRATA O PARTNER:";
        setClipboard(texto);
    }//GEN-LAST:event_btnClienteDesconectadActionPerformed

    private void btnSplitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplitterActionPerformed
        // TODO add your handling code here:
        
        String texto = "TICKET: \n"
                + "CLIENTE(A) COLOCADO EN SPLITTER:\n"
                + "DNI DEL CLIENTE(A) COLOCADO:\n"
                + "-------------------------------------\n"
                + "DNI DEL CLIENTE(A) AFECTADO:\n"
                + "CODIGO DE CTO O PISO DE CAJA NAP:\n"
                + "DIRECCION O NOMBRE DE EDIFICIO / CONDOMINIO / RESIDENCIAL:\n"
                + "PUERTO UTILIZADO:\n"
                + "-------------------------------------\n"
                + "POTENCIA EN EL PUERTO:\n"
                + "POTENCIA EN EL PUERTO CON SPLITTER: \n"
                + "CONTRATA O PARTNER:";
        setClipboard(texto);
    }//GEN-LAST:event_btnSplitterActionPerformed

    private void txtPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuertoActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void cboDistrito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDistrito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDistrito2ActionPerformed

    private void cboContrata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboContrata2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboContrata2ActionPerformed

    private void btnValidacionCableadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidacionCableadoActionPerformed
        // TODO add your handling code here:
        String texto = "TICKET:\n"
                + "NOMBRE DEL CLIENTE(A):\n"
                + "DNI:\n"
                + "CODIGO DE CTO O PISO DE CAJA NAP:\n"
                + "DIRECCION O NOMBRE DE EDIFICIO / CONDOMINIO / RESIDENCIAL:\n"
                + "NUMERO DE PUERTO:\n"
                + "POTENCIA DE PUERTO:\n"
                + "METRAJE UTILIZADO:\n"
                + "NOMBRE DEL TECNICO:\n"
                + "GESTION A REALIZAR: \n"
                + "\n"
                + "1. RECABLEADO A LA MISMA CTO O CAJA NAP\n"
                + "2. CAMBIO DE CTO O CAJA NAP\n"
                + "3. TRASLADO\n"
                + "4. REINSTALACION";
        setClipboard(texto);
    }//GEN-LAST:event_btnValidacionCableadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String texto = "TICKET: \n"
                + "NOMBRE DEL CLIENTE(A):\n"
                + "DNI:\n"
                + "CODIGO DE CTO O PISO DE CAJA NAP:\n"
                + "DIRECCION O NOMBRE DE EDIFICIO / CONDOMINIO / RESIDENCIAL:\n"
                + "PUERTO UTILIZADO:\n"
                + "POTENCIA DE PUERTO UTILIZADO:\n"
                + "DNI DEL CLIENTE AFECTADO:\n"
                + "CONTRATA O PARTNER:";
        setClipboard(texto);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCambiosONTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiosONTActionPerformed
        // TODO add your handling code here:
        String texto = "TICKET:\n"
                + "NOMBRE DEL CLIENTE(A):\n"
                + "DNI:\n"
                + "SN DEL ONT ANTIGUO:\n"
                + "SN DEL ONT NUEVO:\n"
                + "NOMBRE DEL TECNICO:\n"
                + "CONTRATA O PARTNER:\n"
                + "OBSERVACION:";
        setClipboard(texto);
    }//GEN-LAST:event_btnCambiosONTActionPerformed

    private void btnCambiosCTONAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiosCTONAPActionPerformed
        // TODO add your handling code here:
        String texto = "TICKET: \n"
                + "NOMBRE DEL CLIENTE(A): \n"
                + "DNI: \n"
                + "SN DEL ONT ACTUAL:\n"
                + "CODIGO DE CTO O PISO DE CAJA NAP: \n"
                + "DIRECCION O NOMBRE DE EDIFICIO / CONDOMINIO / RESIDENCIAL:\n"
                + "NUMERO DE PUERTO:\n"
                + "NOMBRE DEL TECNICO:\n"
                + "CONTRATA O PARTNER: \n"
                + "OBSERVACION: ";
        setClipboard(texto);
    }//GEN-LAST:event_btnCambiosCTONAPActionPerformed

    private void btnRematriculacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRematriculacionActionPerformed
        // TODO add your handling code here:
        String texto = "TICKET: \n"
                + "NOMBRE DEL CLIENTE(A): \n"
                + "DNI: \n"
                + "SN DEL ONT ACTUAL:\n"
                + "NOMBRE DEL TECNICO:\n"
                + "CONTRATA O PARTNER: \n"
                + "OBSERVACION:";
        setClipboard(texto);
    }//GEN-LAST:event_btnRematriculacionActionPerformed

    private void btnValidacionDanDetecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidacionDanDetecActionPerformed
        // TODO add your handling code here:
        String texto = "NOMBRE DEL CLIENTE(A):\n"
                + "DNI:\n"
                + "TELEFONO:\n"
                + "DIRECCION:\n"
                + "TICKET:\n"
                + "SOLICITUD O DAÑO DETECTADO:\n"
                + "OBSERVACION:";
        setClipboard(texto);
    }//GEN-LAST:event_btnValidacionDanDetecActionPerformed

    private void btnValidacionLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidacionLlamadaActionPerformed
        // TODO add your handling code here:
        String texto = "NOMBRE DEL CLIENTE(A):\n"
                + "DNI:\n"
                + "CONTRATA O PARTNER:\n"
                + "FECHA Y TRAMO SOLICITADO:\n"
                + "NUMERO DE CONTACTO:\n"
                + "MOTIVO:\n"
                + "TICKET: \n"
                + "OBSERVACIONES:";
        setClipboard(texto);
    }//GEN-LAST:event_btnValidacionLlamadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiosCTONAP;
    private javax.swing.JButton btnCambiosONT;
    private javax.swing.JButton btnClienteDesconectad;
    private javax.swing.JButton btnCopiar2;
    private javax.swing.JButton btnCopiarNuevo;
    private javax.swing.JButton btnMostrarTextoGrande;
    private javax.swing.JButton btnRematriculacion;
    private javax.swing.JButton btnSplitter;
    private javax.swing.JButton btnValidacionCableado;
    private javax.swing.JButton btnValidacionDanDetec;
    private javax.swing.JButton btnValidacionLlamada;
    private javax.swing.JComboBox<String> cboContrata;
    private javax.swing.JComboBox<String> cboContrata2;
    private javax.swing.JComboBox<String> cboDistrito;
    private javax.swing.JComboBox<String> cboDistrito2;
    private javax.swing.JComboBox<String> cboMotivo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCoordenadas;
    private javax.swing.JTextField txtCto;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JButton txtLID;
    private javax.swing.JButton txtLID9;
    private javax.swing.JTextField txtNomTecnico;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextArea txtResultado2;
    private javax.swing.JTextArea txtTextoGrande;
    private javax.swing.JTextField txtTicket;
    // End of variables declaration//GEN-END:variables

    @Override
    public void lostOwnership(Clipboard clipboard, Transferable contents) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
